type WeatherCodeObj = {
  code: Number;
  condition: string;
  dayIcon: string;
  nightIcon: string;
};

export const WeatherCodeObjs: WeatherCodeObj[] = [
  {
    code: 395,
    condition: "Moderate or heavy snow in area with thunder",
    dayIcon: "wsymbol_0012_heavy_snow_showers",
    nightIcon: "wsymbol_0028_heavy_snow_showers_night",
  },
  {
    code: 392,
    condition: "Patchy light snow in area with thunder",
    dayIcon: "wsymbol_0016_thundery_showers",
    nightIcon: "wsymbol_0032_thundery_showers_night",
  },
  {
    code: 389,
    condition: "Moderate or heavy rain in area with thunder",
    dayIcon: "wsymbol_0024_thunderstorms",
    nightIcon: "wsymbol_0040_thunderstorms_night",
  },
  {
    code: 386,
    condition: "Patchy light rain in area with thunder",
    dayIcon: "wsymbol_0016_thundery_showers",
    nightIcon: "wsymbol_0032_thundery_showers_night",
  },
  {
    code: 377,
    condition: "Moderate or heavy showers of ice pellets",
    dayIcon: "wsymbol_0021_cloudy_with_sleet",
    nightIcon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: 374,
    condition: "Light showers of ice pellets",
    dayIcon: "wsymbol_0013_sleet_showers",
    nightIcon: "wsymbol_0029_sleet_showers_night",
  },
  {
    code: 371,
    condition: "Moderate or heavy snow showers",
    dayIcon: "wsymbol_0012_heavy_snow_showers",
    nightIcon: "wsymbol_0028_heavy_snow_showers_night",
  },
  {
    code: 368,
    condition: "Light snow showers",
    dayIcon: "wsymbol_0011_light_snow_showers",
    nightIcon: "wsymbol_0027_light_snow_showers_night",
  },
  {
    code: 365,
    condition: "Moderate or heavy sleet showers",
    dayIcon: "wsymbol_0013_sleet_showers",
    nightIcon: "wsymbol_0029_sleet_showers_night",
  },
  {
    code: 362,
    condition: "Light sleet showers",
    dayIcon: "wsymbol_0013_sleet_showers",
    nightIcon: "wsymbol_0029_sleet_showers_night",
  },
  {
    code: 359,
    condition: "Torrential rain shower",
    dayIcon: "wsymbol_0018_cloudy_with_heavy_rain",
    nightIcon: "wsymbol_0034_cloudy_with_heavy_rain_night",
  },
  {
    code: 356,
    condition: "Moderate or heavy rain shower",
    dayIcon: "wsymbol_0010_heavy_rain_showers",
    nightIcon: "wsymbol_0026_heavy_rain_showers_night",
  },
  {
    code: 353,
    condition: "Light rain shower",
    dayIcon: "wsymbol_0009_light_rain_showers",
    nightIcon: "wsymbol_0025_light_rain_showers_night",
  },
  {
    code: 350,
    condition: "Ice pellets",
    dayIcon: "wsymbol_0021_cloudy_with_sleet",
    nightIcon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: 338,
    condition: "Heavy snow",
    dayIcon: "wsymbol_0020_cloudy_with_heavy_snow",
    nightIcon: "wsymbol_0036_cloudy_with_heavy_snow_night",
  },
  {
    code: 335,
    condition: "Patchy heavy snow",
    dayIcon: "wsymbol_0012_heavy_snow_showers",
    nightIcon: "wsymbol_0028_heavy_snow_showers_night",
  },
  {
    code: 332,
    condition: "Moderate snow",
    dayIcon: "wsymbol_0020_cloudy_with_heavy_snow",
    nightIcon: "wsymbol_0036_cloudy_with_heavy_snow_night",
  },
  {
    code: 329,
    condition: "Patchy moderate snow",
    dayIcon: "wsymbol_0020_cloudy_with_heavy_snow",
    nightIcon: "wsymbol_0036_cloudy_with_heavy_snow_night",
  },
  {
    code: 326,
    condition: "Light snow",
    dayIcon: "wsymbol_0011_light_snow_showers",
    nightIcon: "wsymbol_0027_light_snow_showers_night",
  },
  {
    code: 323,
    condition: "Patchy light snow",
    dayIcon: "wsymbol_0011_light_snow_showers",
    nightIcon: "wsymbol_0027_light_snow_showers_night",
  },
  {
    code: 320,
    condition: "Moderate or heavy sleet",
    dayIcon: "wsymbol_0019_cloudy_with_light_snow",
    nightIcon: "wsymbol_0035_cloudy_with_light_snow_night",
  },
  {
    code: 317,
    condition: "Light sleet",
    dayIcon: "wsymbol_0021_cloudy_with_sleet",
    nightIcon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: 314,
    condition: "Moderate or Heavy freezing rain",
    dayIcon: "wsymbol_0021_cloudy_with_sleet",
    nightIcon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: 311,
    condition: "Light freezing rain",
    dayIcon: "wsymbol_0021_cloudy_with_sleet",
    nightIcon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: 308,
    condition: "Heavy rain",
    dayIcon: "wsymbol_0018_cloudy_with_heavy_rain",
    nightIcon: "wsymbol_0034_cloudy_with_heavy_rain_night",
  },
  {
    code: 305,
    condition: "Heavy rain at times",
    dayIcon: "wsymbol_0010_heavy_rain_showers",
    nightIcon: "wsymbol_0026_heavy_rain_showers_night",
  },
  {
    code: 302,
    condition: "Moderate rain",
    dayIcon: "wsymbol_0018_cloudy_with_heavy_rain",
    nightIcon: "wsymbol_0034_cloudy_with_heavy_rain_night",
  },
  {
    code: 299,
    condition: "Moderate rain at times",
    dayIcon: "wsymbol_0010_heavy_rain_showers",
    nightIcon: "wsymbol_0026_heavy_rain_showers_night",
  },
  {
    code: 296,
    condition: "Light rain",
    dayIcon: "wsymbol_0017_cloudy_with_light_rain",
    nightIcon: "wsymbol_0025_light_rain_showers_night",
  },
  {
    code: 293,
    condition: "Patchy light rain",
    dayIcon: "wsymbol_0017_cloudy_with_light_rain",
    nightIcon: "wsymbol_0033_cloudy_with_light_rain_night",
  },
  {
    code: 284,
    condition: "Heavy freezing drizzle",
    dayIcon: "wsymbol_0021_cloudy_with_sleet",
    nightIcon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: 281,
    condition: "Freezing drizzle",
    dayIcon: "wsymbol_0021_cloudy_with_sleet",
    nightIcon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: 266,
    condition: "Light drizzle",
    dayIcon: "wsymbol_0017_cloudy_with_light_rain",
    nightIcon: "wsymbol_0033_cloudy_with_light_rain_night",
  },
  {
    code: 263,
    condition: "Patchy light drizzle",
    dayIcon: "wsymbol_0009_light_rain_showers",
    nightIcon: "wsymbol_0025_light_rain_showers_night",
  },
  {
    code: 260,
    condition: "Freezing fog",
    dayIcon: "wsymbol_0007_fog",
    nightIcon: "wsymbol_0007_fog",
  },
  {
    code: 248,
    condition: "Fog",
    dayIcon: "wsymbol_0007_fog",
    nightIcon: "wsymbol_0007_fog",
  },
  {
    code: 230,
    condition: "Blizzard",
    dayIcon: "wsymbol_0020_cloudy_with_heavy_snow",
    nightIcon: "wsymbol_0036_cloudy_with_heavy_snow_night",
  },
  {
    code: 227,
    condition: "Blowing snow",
    dayIcon: "wsymbol_0019_cloudy_with_light_snow",
    nightIcon: "wsymbol_0035_cloudy_with_light_snow_night",
  },
  {
    code: 200,
    condition: "Thundery outbreaks in nearby",
    dayIcon: "wsymbol_0016_thundery_showers",
    nightIcon: "wsymbol_0032_thundery_showers_night",
  },
  {
    code: 185,
    condition: "Patchy freezing drizzle nearby",
    dayIcon: "wsymbol_0021_cloudy_with_sleet",
    nightIcon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: 182,
    condition: "Patchy sleet nearby",
    dayIcon: "wsymbol_0021_cloudy_with_sleet",
    nightIcon: "wsymbol_0037_cloudy_with_sleet_night",
  },
  {
    code: 179,
    condition: "Patchy snow nearby",
    dayIcon: "wsymbol_0013_sleet_showers",
    nightIcon: "wsymbol_0029_sleet_showers_night",
  },
  {
    code: 176,
    condition: "Patchy rain nearby",
    dayIcon: "wsymbol_0009_light_rain_showers",
    nightIcon: "wsymbol_0025_light_rain_showers_night",
  },
  {
    code: 143,
    condition: "Mist",
    dayIcon: "wsymbol_0006_mist",
    nightIcon: "wsymbol_0006_mist",
  },
  {
    code: 122,
    condition: "Overcast",
    dayIcon: "wsymbol_0004_black_low_cloud",
    nightIcon: "wsymbol_0004_black_low_cloud",
  },
  {
    code: 119,
    condition: "Cloudy",
    dayIcon: "wsymbol_0003_white_cloud",
    nightIcon: "wsymbol_0004_black_low_cloud",
  },
  {
    code: 116,
    condition: "Partly Cloudy",
    dayIcon: "wsymbol_0002_sunny_intervals",
    nightIcon: "wsymbol_0008_clear_sky_night",
  },
  {
    code: 113,
    condition: "Clear/Sunny",
    dayIcon: "wsymbol_0001_sunny",
    nightIcon: "wsymbol_0008_clear_sky_night",
  },
];
